### PR TITLE
Variation: simple with darkmode

### PR DESCRIPTION
**Pull request by margalit**
👋 Heya Alice

This an MR for a variation on your design with some style tweaks as well as support for darkmode. The justification for my design changes were to enforce consistency through a standardized spacing scale (borrowed from [tailwind](https://tailwindcss.com/docs/customizing-spacing#default-spacing-scale)), rejigging the font sizes and layout to support mobile views without adding media queries and minimizing the visual differences between dark and light mode.

Some other changes include:
- Move colors and spacing into css variables for ease of development
- Replace logo background and text name with combined logo and logotype svg to reduce visual noise
- Support dark mode variation through querying `prefers-color-scheme: dark`

I opted to swap the background on the cards in light mode from the brand color to white with a brand color border, mainly to reduce the number of color variables to toggle between light/mode. However I think I prefer your version with white text on a brand color so this might be a good candidate to compare the two in a preference test on UsabilityHub.

Also, I’ve implemented some very basic hover styles since I was mainly focusing on getting the hierarchy of the information right and would love to revisit this with you.

Still to do:
- [ ] Test usability on usabilityhub.com
- [ ] Accessibility review
- [ ] Extract class styles to inline styles

## Darkmode (desktop + mobile)
Screen Shot 2021-08-01 at 01 05 41

## Lightmode (desktop + mobile)
Screen Shot 2021-08-01 at 01 06 07

Looking forward to hearing your thoughts and where we might go next on them? Maybe you’d like to use this as a basis for designing another variation to test?

Sam

### CODE REVIEW

**Comment by alicelovescake** [comment]
@margalit  This is great. You've done a ton of work! Your version looks clean and simple. I was wondering if there is a way to keep the acorn in the background original like my version? I feel like that was the one piece making the original unique. Visual noise could possibly be reduced in other ways (like tweaking opacity). If not, oh well I guess.

I definitely prefer having the brand color as the background of the cards. Perhaps the dark mode version could use the light brand color for background with dark text? I like that we can test which version the user would like better. 

So how do we proceed with the usability testing?  Do you want me to merge first or after you get the results? Let me know how I can help!

**Comment by alicelovescake** [comment]
Also, perhaps we could make the social icons less noticeable. They became a lot more prominent in your design but it feels like they should be less prominent?

**Comment by margalit** [comment]
Hiya Alice, thanks for the feedback and the kind words!

Totally agree with brand color on the background of the cards for light mode. I think this could warrant a custom dark mode selector style. For dark mode, my preference is to generally keep contrast low but I think that the brand color would work well as a hover style.

Also agree with de-emphasising the social links, how about moving to the footer? Either above or below the version number.

Here’s how it looks on desktop with both those suggestions (first card hovered): 
Screenshot 2021-08-01 at 14-11-03 Welcome to RedwoodJS
Screenshot 2021-08-01 at 14-10-45 Welcome to RedwoodJS

I think these are both good improvements and brings the balance back to the light mode from your original design. What do you think?

I’ll follow up shortly with an variation that moves the pinecone from beside the logotype back into the background like your original design.

**Comment by margalit** [comment]
Here’s an alternative that moves the logo from beside the type to the background like in your original design, for clarity I’ll call this the **logo background variation** and the one above the **logotype variation**.

Screenshot 2021-08-01 at 14-03-18 Welcome to RedwoodJS
Screenshot 2021-08-01 at 14-02-43 Welcome to RedwoodJS

I think this is very nice! It could work in a few different placements. I’ll push this to a branch ` logo-background-variation` so you can play with some alternative positions.

Edit: [here’s a link to the branch](Here’s a link to the logo background variation as a branch you can pull down and have a play with: https://github.com/margalit/redwood-splashpage/tree/logo-background-variation)

**Comment by margalit** [comment]
It looks like we’re emerging with two variations for testing: `logotype` and `logo-background`. This could be a good opportunity to test them in UsabilityHub, probably with a [preference test](https://usabilityhub.com/product/preference-tests) (ie. which design do you prefer?) since I can’t see either variation having much of an impact on the usability of the site. We can present both variations, side by side and have the testers click which design the prefer. We can follow up with a "why did you choose that one?" question for more detail.

Once we’ve settled on a design we can test the usability of the site. Off the top of my I’m thinking we focus mainly on making sure users **know what they need to do to progress** and **how to get help**. We can use [First click test](https://usabilityhub.com/product/first-click-tests) to see where a user would go.

## Primary
- Where would you click to proceed?
- How easy was that to find?
- How confident are you that you’re correct?
- Where would you click to get help?
- How easy was that to find?
- How confident are you that you’re correct?

## Secondary
- What is the name of the brand?
- What version of the software is running?

This should surface any red flags that would either prevent the user from continuing and/or finding help if they are stuck.

Is there any thing else you think we should test? We could ask "why are you seeing this page" but it’s a little redundant since the first line is "You’re seeing this page because...".

**Comment by margalit** [comment]
> Here’s an alternative that moves the logo from beside the type to the background like in your original design, for clarity I’ll call this the **logo background variation** and the one above the **logotype variation**.
> 
> localhost_5000_(iPad Pro) (2)
> localhost_5000_(iPad Pro) (1)
> 
> I think this is nice and could work in a few different placements. I’ll push this to a branch ` logo-background-variation` so you can play with some alternative positions.

Here’s a link to the logo background variation as a branch you can pull down and have a play with: https://github.com/margalit/redwood-splashpage/tree/logo-background-variation

**Comment by margalit** [comment]
Sorry for drowning you in comments! Last one promise:

Here’s a design that combines both variations—I think it’s my favourite:

Screenshot 2021-08-01 at 14-15-03 Welcome to RedwoodJS
Screenshot 2021-08-01 at 14-14-34 Welcome to RedwoodJS

**Comment by alicelovescake** [comment]
@margalit Love the new variations! Thanks for taking my feedback! Both versions are great.

1. The social logos definitely looks better being on the bottom. 
2. I like the `logo-background-variation` because it feels a bit special even though we are not designers haha. I like your position of the acorn, it feels clean and subtle, which I think all good designs are. 

Do you want to create a PR for the `logo-background-variation` and I can merge it? 

After that, we can create a PR for the Redwood repo and get any feedback from the community!

**Comment by margalit** [comment]
Closing this MR and moving discussion to https://github.com/alicelovescake/redwood-splashpage/pull/2

**Pull request closed without merging**
